### ISSUE TITLE
[US] As an administrator, I want to remove facilities that violate app policy.

### ISSUE THREAD

**Issue by sophiacabungcal** [CMPUT301F24throat/throat-events#41]
### Tasks
- [ ] define meaning of "violating app policy"
- [ ] create a view that displays all facilities which can be selected & deleted by an admin
- consider what this view displays; if this view should be searchable (maybe by events? by owner/organizer?) etc..
- [ ] define & implement logic for deleting a facility
- what will it mean for existing, current, and future events tied to that facility? will the organizer who "owns" that facility be notified? and other scenarios

### Acceptance Criteria
- Proper User Role: only users with the Admin role should be able to perform this action
- Backend: logic properly handling user role, consequences / impact of removing a facility
- UI: view that displays ALL facilities which the admin browses, selects & deletes from

<img width="196" alt="Screenshot 2024-10-31 at 12 56 27" src="https://github.com/user-attachments/assets/d1543c30-ebbc-4c1a-abad-3bc832928bfb">

**Comment by sophiacabungcal** [comment]
### Tasks
- [ ] define what "violating app policy" means
- [ ] create a view of all existing facilities that can be selected and deleted by a user in the admin role
- [ ] define and implement logic for deleting a facility: what will it mean for existing, current, and future events tied to that facility? will the organizer who "owns" that facility be notified? and other scenarios

### Acceptance Criteria
- [ ] only users with the Admin role should be able to perform this action (remove facilities violating app policy)
- [ ] separate view that displays ALL facilities which the admin selects from
- [ ] consequences / impact of removing a facility: facility events (and its registrants), and its owners
